<?php

return [
    'new-york' => ['city' => 'New York', 'country' => 'United States', 'timezone' => 'America/New_York', 'latitude' => 40.7128, 'longitude' => -74.0060],
    'los-angeles' => ['city' => 'Los Angeles', 'country' => 'United States', 'timezone' => 'America/Los_Angeles', 'latitude' => 34.0522, 'longitude' => -118.2437],
    'chicago' => ['city' => 'Chicago', 'country' => 'United States', 'timezone' => 'America/Chicago', 'latitude' => 41.8781, 'longitude' => -87.6298],
    'houston' => ['city' => 'Houston', 'country' => 'United States', 'timezone' => 'America/Chicago', 'latitude' => 29.7604, 'longitude' => -95.3698],
    'phoenix' => ['city' => 'Phoenix', 'country' => 'United States', 'timezone' => 'America/Phoenix', 'latitude' => 33.4484, 'longitude' => -112.0740],
    'philadelphia' => ['city' => 'Philadelphia', 'country' => 'United States', 'timezone' => 'America/New_York', 'latitude' => 39.9526, 'longitude' => -75.1652],
    'san-antonio' => ['city' => 'San Antonio', 'country' => 'United States', 'timezone' => 'America/Chicago', 'latitude' => 29.4241, 'longitude' => -98.4936],
    'san-diego' => ['city' => 'San Diego', 'country' => 'United States', 'timezone' => 'America/Los_Angeles', 'latitude' => 32.7157, 'longitude' => -117.1611],
    'dallas' => ['city' => 'Dallas', 'country' => 'United States', 'timezone' => 'America/Chicago', 'latitude' => 32.7767, 'longitude' => -96.7970],
    'san-jose' => ['city' => 'San Jose', 'country' => 'United States', 'timezone' => 'America/Los_Angeles', 'latitude' => 37.3382, 'longitude' => -121.8863],
    'austin' => ['city' => 'Austin', 'country' => 'United States', 'timezone' => 'America/Chicago', 'latitude' => 30.2672, 'longitude' => -97.7431],
    'san-francisco' => ['city' => 'San Francisco', 'country' => 'United States', 'timezone' => 'America/Los_Angeles', 'latitude' => 37.7749, 'longitude' => -122.4194],
    'seattle' => ['city' => 'Seattle', 'country' => 'United States', 'timezone' => 'America/Los_Angeles', 'latitude' => 47.6062, 'longitude' => -122.3321],
    'denver' => ['city' => 'Denver', 'country' => 'United States', 'timezone' => 'America/Denver', 'latitude' => 39.7392, 'longitude' => -104.9903],
    'boston' => ['city' => 'Boston', 'country' => 'United States', 'timezone' => 'America/New_York', 'latitude' => 42.3601, 'longitude' => -71.0589],
    'las-vegas' => ['city' => 'Las Vegas', 'country' => 'United States', 'timezone' => 'America/Los_Angeles', 'latitude' => 36.1699, 'longitude' => -115.1398],
    'miami' => ['city' => 'Miami', 'country' => 'United States', 'timezone' => 'America/New_York', 'latitude' => 25.7617, 'longitude' => -80.1918],
    'atlanta' => ['city' => 'Atlanta', 'country' => 'United States', 'timezone' => 'America/New_York', 'latitude' => 33.7490, 'longitude' => -84.3880],
    'washington-dc' => ['city' => 'Washington, DC', 'country' => 'United States', 'timezone' => 'America/New_York', 'latitude' => 38.9072, 'longitude' => -77.0369],
    'nashville' => ['city' => 'Nashville', 'country' => 'United States', 'timezone' => 'America/Chicago', 'latitude' => 36.1627, 'longitude' => -86.7816],
    'portland' => ['city' => 'Portland', 'country' => 'United States', 'timezone' => 'America/Los_Angeles', 'latitude' => 45.5152, 'longitude' => -122.6784],
    'new-orleans' => ['city' => 'New Orleans', 'country' => 'United States', 'timezone' => 'America/Chicago', 'latitude' => 29.9511, 'longitude' => -90.0715],
    'toronto' => ['city' => 'Toronto', 'country' => 'Canada', 'timezone' => 'America/Toronto', 'latitude' => 43.6532, 'longitude' => -79.3832],
    'montreal' => ['city' => 'Montreal', 'country' => 'Canada', 'timezone' => 'America/Toronto', 'latitude' => 45.5019, 'longitude' => -73.5674],
    'vancouver' => ['city' => 'Vancouver', 'country' => 'Canada', 'timezone' => 'America/Vancouver', 'latitude' => 49.2827, 'longitude' => -123.1207],
    'calgary' => ['city' => 'Calgary', 'country' => 'Canada', 'timezone' => 'America/Edmonton', 'latitude' => 51.0447, 'longitude' => -114.0719],
    'ottawa' => ['city' => 'Ottawa', 'country' => 'Canada', 'timezone' => 'America/Toronto', 'latitude' => 45.4215, 'longitude' => -75.6972],
    'edmonton' => ['city' => 'Edmonton', 'country' => 'Canada', 'timezone' => 'America/Edmonton', 'latitude' => 53.5461, 'longitude' => -113.4938],
    'quebec-city' => ['city' => 'Quebec City', 'country' => 'Canada', 'timezone' => 'America/Toronto', 'latitude' => 46.8139, 'longitude' => -71.2080],
    'winnipeg' => ['city' => 'Winnipeg', 'country' => 'Canada', 'timezone' => 'America/Winnipeg', 'latitude' => 49.8951, 'longitude' => -97.1384],
    'mexico-city' => ['city' => 'Mexico City', 'country' => 'Mexico', 'timezone' => 'America/Mexico_City', 'latitude' => 19.4326, 'longitude' => -99.1332],
    'guadalajara' => ['city' => 'Guadalajara', 'country' => 'Mexico', 'timezone' => 'America/Mexico_City', 'latitude' => 20.6597, 'longitude' => -103.3496],
    'monterrey' => ['city' => 'Monterrey', 'country' => 'Mexico', 'timezone' => 'America/Monterrey', 'latitude' => 25.6866, 'longitude' => -100.3161],
    'puebla' => ['city' => 'Puebla', 'country' => 'Mexico', 'timezone' => 'America/Mexico_City', 'latitude' => 19.0414, 'longitude' => -98.2063],
    'tijuana' => ['city' => 'Tijuana', 'country' => 'Mexico', 'timezone' => 'America/Tijuana', 'latitude' => 32.5149, 'longitude' => -117.0382],
    'cancun' => ['city' => 'Cancun', 'country' => 'Mexico', 'timezone' => 'America/Cancun', 'latitude' => 21.1619, 'longitude' => -86.8515],
    'merida' => ['city' => 'Merida', 'country' => 'Mexico', 'timezone' => 'America/Merida', 'latitude' => 20.9674, 'longitude' => -89.5926],
    'london' => ['city' => 'London', 'country' => 'United Kingdom', 'timezone' => 'Europe/London', 'latitude' => 51.5074, 'longitude' => -0.1278],
    'paris' => ['city' => 'Paris', 'country' => 'France', 'timezone' => 'Europe/Paris', 'latitude' => 48.8566, 'longitude' => 2.3522],
    'berlin' => ['city' => 'Berlin', 'country' => 'Germany', 'timezone' => 'Europe/Berlin', 'latitude' => 52.5200, 'longitude' => 13.4050],
    'madrid' => ['city' => 'Madrid', 'country' => 'Spain', 'timezone' => 'Europe/Madrid', 'latitude' => 40.4168, 'longitude' => -3.7038],
    'rome' => ['city' => 'Rome', 'country' => 'Italy', 'timezone' => 'Europe/Rome', 'latitude' => 41.9028, 'longitude' => 12.4964],
    'amsterdam' => ['city' => 'Amsterdam', 'country' => 'Netherlands', 'timezone' => 'Europe/Amsterdam', 'latitude' => 52.3676, 'longitude' => 4.9041],
    'barcelona' => ['city' => 'Barcelona', 'country' => 'Spain', 'timezone' => 'Europe/Madrid', 'latitude' => 41.3851, 'longitude' => 2.1734],
    'munich' => ['city' => 'Munich', 'country' => 'Germany', 'timezone' => 'Europe/Berlin', 'latitude' => 48.1351, 'longitude' => 11.5820],
    'milan' => ['city' => 'Milan', 'country' => 'Italy', 'timezone' => 'Europe/Rome', 'latitude' => 45.4642, 'longitude' => 9.1900],
    'vienna' => ['city' => 'Vienna', 'country' => 'Austria', 'timezone' => 'Europe/Vienna', 'latitude' => 48.2082, 'longitude' => 16.3738],
    'prague' => ['city' => 'Prague', 'country' => 'Czech Republic', 'timezone' => 'Europe/Prague', 'latitude' => 50.0755, 'longitude' => 14.4378],
    'lisbon' => ['city' => 'Lisbon', 'country' => 'Portugal', 'timezone' => 'Europe/Lisbon', 'latitude' => 38.7223, 'longitude' => -9.1393],
    'dublin' => ['city' => 'Dublin', 'country' => 'Ireland', 'timezone' => 'Europe/Dublin', 'latitude' => 53.3498, 'longitude' => -6.2603],
    'copenhagen' => ['city' => 'Copenhagen', 'country' => 'Denmark', 'timezone' => 'Europe/Copenhagen', 'latitude' => 55.6761, 'longitude' => 12.5683],
    'stockholm' => ['city' => 'Stockholm', 'country' => 'Sweden', 'timezone' => 'Europe/Stockholm', 'latitude' => 59.3293, 'longitude' => 18.0686],
    'oslo' => ['city' => 'Oslo', 'country' => 'Norway', 'timezone' => 'Europe/Oslo', 'latitude' => 59.9139, 'longitude' => 10.7522],
    'helsinki' => ['city' => 'Helsinki', 'country' => 'Finland', 'timezone' => 'Europe/Helsinki', 'latitude' => 60.1699, 'longitude' => 24.9384],
    'brussels' => ['city' => 'Brussels', 'country' => 'Belgium', 'timezone' => 'Europe/Brussels', 'latitude' => 50.8503, 'longitude' => 4.3517],
    'zurich' => ['city' => 'Zurich', 'country' => 'Switzerland', 'timezone' => 'Europe/Zurich', 'latitude' => 47.3769, 'longitude' => 8.5417],
    'warsaw' => ['city' => 'Warsaw', 'country' => 'Poland', 'timezone' => 'Europe/Warsaw', 'latitude' => 52.2297, 'longitude' => 21.0122],
    'budapest' => ['city' => 'Budapest', 'country' => 'Hungary', 'timezone' => 'Europe/Budapest', 'latitude' => 47.4979, 'longitude' => 19.0402],
    'athens' => ['city' => 'Athens', 'country' => 'Greece', 'timezone' => 'Europe/Athens', 'latitude' => 37.9838, 'longitude' => 23.7275],
    'lyon' => ['city' => 'Lyon', 'country' => 'France', 'timezone' => 'Europe/Paris', 'latitude' => 45.7640, 'longitude' => 4.8357],
    'hamburg' => ['city' => 'Hamburg', 'country' => 'Germany', 'timezone' => 'Europe/Berlin', 'latitude' => 53.5511, 'longitude' => 9.9937],
    'manchester' => ['city' => 'Manchester', 'country' => 'United Kingdom', 'timezone' => 'Europe/London', 'latitude' => 53.4808, 'longitude' => -2.2426],
    'edinburgh' => ['city' => 'Edinburgh', 'country' => 'United Kingdom', 'timezone' => 'Europe/London', 'latitude' => 55.9533, 'longitude' => -3.1883],
    'frankfurt' => ['city' => 'Frankfurt', 'country' => 'Germany', 'timezone' => 'Europe/Berlin', 'latitude' => 50.1109, 'longitude' => 8.6821],
    'krakow' => ['city' => 'Krakow', 'country' => 'Poland', 'timezone' => 'Europe/Warsaw', 'latitude' => 50.0647, 'longitude' => 19.9450],
    'porto' => ['city' => 'Porto', 'country' => 'Portugal', 'timezone' => 'Europe/Lisbon', 'latitude' => 41.1579, 'longitude' => -8.6291],
    'naples' => ['city' => 'Naples', 'country' => 'Italy', 'timezone' => 'Europe/Rome', 'latitude' => 40.8518, 'longitude' => 14.2681],
    'tokyo' => ['city' => 'Tokyo', 'country' => 'Japan', 'timezone' => 'Asia/Tokyo', 'latitude' => 35.6762, 'longitude' => 139.6503],
    'seoul' => ['city' => 'Seoul', 'country' => 'South Korea', 'timezone' => 'Asia/Seoul', 'latitude' => 37.5665, 'longitude' => 126.9780],
    'singapore' => ['city' => 'Singapore', 'country' => 'Singapore', 'timezone' => 'Asia/Singapore', 'latitude' => 1.3521, 'longitude' => 103.8198],
    'sydney' => ['city' => 'Sydney', 'country' => 'Australia', 'timezone' => 'Australia/Sydney', 'latitude' => -33.8688, 'longitude' => 151.2093],
    'melbourne' => ['city' => 'Melbourne', 'country' => 'Australia', 'timezone' => 'Australia/Melbourne', 'latitude' => -37.8136, 'longitude' => 144.9631],
    'dubai' => ['city' => 'Dubai', 'country' => 'United Arab Emirates', 'timezone' => 'Asia/Dubai', 'latitude' => 25.2048, 'longitude' => 55.2708],
    'sao-paulo' => ['city' => 'Sao Paulo', 'country' => 'Brazil', 'timezone' => 'America/Sao_Paulo', 'latitude' => -23.5505, 'longitude' => -46.6333],
    'buenos-aires' => ['city' => 'Buenos Aires', 'country' => 'Argentina', 'timezone' => 'America/Argentina/Buenos_Aires', 'latitude' => -34.6037, 'longitude' => -58.3816],
];
